doc(api): Add api documentation
Prophecy-eip/Backend pull request #24
Opened 2022-05-04 18:53 UTC by Victoire-Rabeau

# How to review ?

Open a review in the pull request

## Read the documentation
- Go to the [swagger documentation](https://app.swaggerhub.com/apis/Victoire-Rabeau/Prophecy/1.0.0)
- Navigate through the documentation using the graphical interface
- If there is nothing to report, approve the pull request using the review

#### Note
All the schemas information are available in the `Schema` section of the documentation 

## Report something
If you need to report something (bug, missing information(s), ...):
- Start a review in the pull request
- In the swagger documentation, go to the route in the editor using the `View in Editor` button
![image](https://user-images.githubusercontent.com/67317051/168084259-7004ba85-5d82-4046-bc66-1939474139ae.png)
- Check the number(s) of the line(s) to report and report in the `api-swagger` document using the review explaining what is the requested change
- Continue reading the documentation and report other bugs if necessary
- Once you are done, request changes and submit the review

## What to check ?
Please check that:
- The routes' methods are correct
- The routes' paths are correct
- The routes' summaries are complete and consistent
- There is no missing parameter
- There is no missing data in the request body
- There is no missing data in the responses
Feel free to suggest any changes that you feel are relevant

---
Closes #10

2022-05-14 15:05 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:05 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:06 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:06 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:06 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:06 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:06 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:07 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:07 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:07 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:08 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:08 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:08 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:08 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:08 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:09 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:09 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:09 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:09 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:09 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:09 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:09 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:09 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:09 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:09 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:10 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:10 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:10 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:10 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:10 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:10 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:10 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:11 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:12 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:12 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:12 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:12 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:12 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:12 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:12 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:13 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:13 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:13 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:13 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:13 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:13 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:13 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 15:13 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
description ?

2022-05-14 20:43 UTC, Pepiloto reviewed
Is it possible to separe the different parts in multiple files ? Like one file for Events, one for Account ? It's just to increase readibility, it's not very important

2022-05-14 20:43 UTC, Pepiloto commented on doc/api/api-swagger.yml
> +      type: string
Do we need to precise that it's hashed ? And if it is do we need to precise the hash ?

2022-05-14 20:43 UTC, Pepiloto commented on doc/api/api-swagger.yml
> +      example: "YYYY-MM-DD/HH:MM"
Why the dateTime and the time have a different format for the hours and minutes ?

2022-05-14 20:43 UTC, Pepiloto commented on doc/api/api-swagger.yml
> +        - locationId
Maybe add the owner email address (maybe not required but can be a nice way to ask questions about the event)

2022-05-14 20:43 UTC, Pepiloto commented on doc/api/api-swagger.yml
> +        - address
Maybe add an email address or a phone number (not required but if the owner wants to put a contact)

2022-05-14 20:43 UTC, Pepiloto commented on doc/api/api-swagger.yml
> +        - members
Maybe add a size value that will be changed every time a new member is added/removed

2022-05-14 20:43 UTC, Pepiloto commented on doc/api/api-swagger.yml
> +        - arm
Missing aegis stat (it's the special armor

2022-05-14 20:43 UTC, Pepiloto commented on doc/api/api-swagger.yml
> +          description: 'Armour: The innate Armour of the model'
```suggestion
          description: 'Armour: The innate Armour of the unit
```

2022-05-14 20:43 UTC, Pepiloto commented on doc/api/api-swagger.yml
> +                - $ref: '#/components/schemas/size'
Shouldn't the name, the army category and the cost be required ?

2022-05-15 13:23 UTC, Jordan-B1 requested changes

2022-05-15 21:01 UTC, n0no123 requested changes

2022-05-19 08:26 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +
why ?

2022-05-19 08:27 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +        401:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2022-05-19 08:29 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
- usernames are not unique
- what would an invalid username be ?

2022-05-19 08:29 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +        401:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2022-05-19 08:38 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +        - password
usernames are not unique, so it's not possible

2022-05-19 08:39 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +  /account/profile/posts/create-post:
Posts are the pictures the user shares

2022-05-19 08:40 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +  /locations/{locationId}/events/get-events:
This route must be used to retrieve the events from a specific location (a game bar, a shop, ...)

2022-05-19 08:41 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +  /armies/{armyId}/get-organisation:
![image](https://user-images.githubusercontent.com/67317051/169251575-4ad3a2c9-e2c6-4057-a53b-ca31f4852b25.png)

2022-05-19 08:44 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +  # TEAMS
I don't think that request to be in a team is usefull, I was inspired by discord servers

Ban might be a feature, but we don't need it now

2022-05-19 08:46 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      type: string
https://github.com/Prophecy-eip/Backend/pull/24#discussion_r872979417

2022-05-19 08:48 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +        - members
this value does not have to be stored by the server and ca easily be calculated by the client if required, I don't think it is usefull

2022-05-19 08:49 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          description: 'Armour: The innate Armour of the model'
just copied The IXth age's core rules...

2022-05-19 08:49 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +    post:
usernames are not unique, so it is not possible

2022-05-19 08:53 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +  /account/sign-out:
Isn't the user authenticated by the bearer token ?

2022-05-19 09:04 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
The user cannot share other users lists, they are not stored at the same emplacement and they cannot access each other lists

2022-05-19 09:05 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +
The user cannot share other users lists, they are not stored at the same emplacement and they cannot access each other lists

2022-05-19 09:05 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +
The user cannot share other users lists, they are not stored at the same emplacement and they cannot access each other lists

2022-05-19 09:08 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
The user cannot share other users games, they are not stored at the same emplacement and they cannot access each other lists

2022-05-19 09:08 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
The user cannot share other users games, they are not stored at the same emplacement and they cannot access each other lists

2022-05-19 09:16 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +
The users cannot access each other's data because they are not stored at the same emplacement -> Not found

2022-05-19 09:16 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +
The users cannot access each other's data because they are not stored at the same emplacement -> Not found

2022-05-19 09:25 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
user not found ?

2022-05-19 09:31 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 09:31 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 09:31 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 09:33 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 09:33 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2022-05-19 09:33 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2022-05-19 09:37 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 09:41 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2022-05-19 09:41 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

2022-05-19 09:43 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2022-05-19 09:43 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

2022-05-19 09:43 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2022-05-19 09:43 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

2022-05-19 09:44 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
No saved events ?

2022-05-19 09:45 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2022-05-19 09:47 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +    put:
?

2022-05-19 09:53 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

2022-05-19 09:53 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/forbiddenResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

2022-05-19 09:53 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2022-05-19 09:54 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 09:54 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 09:55 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 09:55 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 09:56 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2022-05-19 09:56 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/notFoundResponse'
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

2022-05-19 09:57 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 09:57 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 09:57 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 09:57 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 12:32 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 12:32 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 12:32 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 12:33 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 12:33 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 12:33 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 12:33 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 12:33 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 12:33 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 12:33 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 12:33 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      description: ""
Descriptions are still in the document because I could use them to describe more the route once it is implemented

2022-05-19 13:10 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
I think it's the client's job (let's see with @n0no123 and @aurelien-boch)

2022-05-19 13:20 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +      type: string
No we don't, the password is hashed by the server, not the client

2022-05-19 14:38 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +          $ref: '#/components/schemas/unauthorizedResponse'
discussed in DM

2022-05-19 14:39 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +
same than games

2022-05-19 14:41 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +
same than games

2022-05-19 14:41 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +
same than games

2022-05-19 14:43 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +
same than games

2022-05-20 17:08 UTC, n0no123 requested changes
How to search (base on an input) and add friend?
I don't see anywhere the notion of friends / contact. Did I miss it or not?

2022-05-20 17:08 UTC, n0no123 commented on doc/api/api-swagger.yml
> +      summary: Retrieves a users ids list
I find the phrasing disturbing.
Does this route return every userId?
Is there a way to find a user base on a partial input? (->how to search user to add friend)

2022-05-21 14:29 UTC, aurelien-boch approved these changes

2022-05-22 18:36 UTC, n0no123 commented on doc/api/api-swagger.yml
> +  /account/profile/update-picture:
How to remove the picture?

2022-05-22 19:37 UTC, n0no123 commented on doc/api/api-swagger.yml
> +  /account/profile/update-picture:
How to get picture?

2022-05-24 21:04 UTC, Pepiloto commented on doc/api/api-swagger.yml
> +        - members
I think we shouldn't do any calculation in the front and use the back as much as possible

2022-05-26 15:54 UTC, n0no123 commented on doc/api/api-swagger.yml
> +  /event/update-event/{eventId}:
**typo:** missing 's'
**expected:** /events/update-event/{eventId}
**got:** /event/update-event/{eventId}

2022-05-26 15:55 UTC, n0no123 reviewed
typo line 279

2022-05-26 16:04 UTC, n0no123 commented on doc/api/api-swagger.yml
> +  /events/get-event/{eventId}:
The object you return doesn't possess an id field, is it:
- a typo
- you send us the object without the id field
- the object you send us is different from the one in db
- you forgot to add the field

2022-05-26 16:49 UTC, n0no123 commented on doc/api/api-swagger.yml
> +  /armies/{armyId}/units/get-unit/{unitId}:
why do we need to access the army table to access the unit?
couldn't we have a /units/get-unit/{unitId}?

2022-05-26 17:32 UTC, n0no123 commented on doc/api/api-swagger.yml
> +  /armies/{armyId}/get-organisation:
plural? as the endpoint return an array

2022-05-26 17:50 UTC, n0no123 commented on doc/api/api-swagger.yml
> +      summary: Retrieves the prophecies histrory
**typo:** too many letters 'r'
**expected:** history
**got:** histrory

2022-05-27 08:04 UTC, n0no123 commented on doc/api/api-swagger.yml
> +  /game/delete-game/{gameId}:
**typo:** missing 's'
**expected:** /games/delete-game/{gameId}
**got:** /game/delete-game/{gameId}

2022-05-27 09:36 UTC, n0no123 commented on doc/api/api-swagger.yml
> +  /users/{userId}/profile/posts/get-posts:
missing route get-post

2022-05-27 12:25 UTC, n0no123 commented on doc/api/api-swagger.yml
> +  /statistics/create-statistic:
missing route: put /statistics/update-statistic/{statisticId}

2022-05-27 12:37 UTC, n0no123 commented on doc/api/api-swagger.yml
> +      summary: Restrieves the location's events list
**typo:** too many letters 's'
**expected:** Retrieves
**got:** Restrieves

2022-05-27 13:45 UTC, n0no123 commented on doc/api/api-swagger.yml
> +  /teams/{teamId}/create-message:
requested body require "messageId" but the "messageId" is returned by the call

2022-05-27 14:05 UTC, n0no123 commented on doc/api/api-swagger.yml
> +        $ref: '#/components/schemas/unauthorizedResponse'
missing line in yml: (between l1521 && l1522) -> "401:"

2022-05-28 17:18 UTC, Victoire-Rabeau commented on doc/api/api-swagger.yml
> +  /account/profile/update-picture:
You can retrieve the picture by using the [/users/get-user/{userId}](https://app.swaggerhub.com/apis/Victoire-Rabeau/Prophecy/1.0.0#/users/get_users_get_user__userId_) route

2022-05-28 21:33 UTC, Pepiloto commented on doc/api/api-swagger.yml
> +        - members
up

2022-05-30 17:27 UTC, aurelien-boch requested changes
account confirmation link missing

2022-05-30 17:27 UTC, aurelien-boch commented on doc/api/api-swagger.yml
> +                $ref: '#/components/schemas/connectionResponse'
register should not login the user. it should send a mail containing an account confirmation link which, will activate the account AND login the user.

2022-06-19 12:50 UTC, merged